DROP TABLE TB_CLIENTE IF EXISTS;
DROP TABLE TB_PRODUTO IF EXISTS;
DROP TABLE TB_PEDIDO_ITEM IF EXISTS;
DROP TABLE TB_PEDIDO_STATUS IF EXISTS;
DROP TABLE TB_PEDIDO IF EXISTS;

CREATE TABLE TB_CLIENTE (
  ID_CLIENTE MEDIUMINT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(200),
  ENDERECO VARCHAR(200),
  PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE TB_PRODUTO (
  ID_PRODUTO MEDIUMINT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(200),
  PRECO NUMBER,
  PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE TB_PEDIDO_STATUS (
  ID_STATUS MEDIUMINT NOT NULL AUTO_INCREMENT,
  DS_STATUS VARCHAR2(200),
  PRIMARY KEY (ID_STATUS)
);

CREATE TABLE TB_PEDIDO (
  ID_PEDIDO MEDIUMINT NOT NULL AUTO_INCREMENT,
  ID_STATUS NUMBER,
  DT_PEDIDO DATE,
  ID_CLIENTE NUMBER,
  PRIMARY KEY (ID_PEDIDO),
  FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
  FOREIGN KEY (ID_STATUS) REFERENCES TB_PEDIDO_STATUS(ID_STATUS)
);

CREATE TABLE TB_PEDIDO_ITEM (
  ID_PEDIDO NUMBER,
  ID_PRODUTO NUMBER,
  QUANTIDADE NUMBER,
  PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
  FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO(ID_PEDIDO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
);

INSERT INTO TB_CLIENTE (NOME, ENDERECO) VALUES ('Fernando', 'Muito longe');
INSERT INTO TB_CLIENTE (NOME, ENDERECO) VALUES ('Willian', NULL);
INSERT INTO TB_CLIENTE (NOME, ENDERECO) VALUES ('João', 'Av. Corifeu de Azevedo Marques, 3097, 05339-900 Butantã - São Paulo - SP');
INSERT INTO TB_CLIENTE (NOME, ENDERECO) VALUES ('Jefferson', 'Av. Corifeu de Azevedo Marques, 3097, 05339-900 Butantã - São Paulo - SP');

INSERT INTO TB_PRODUTO (NOME, PRECO) VALUES ('Arroz', 5);
INSERT INTO TB_PRODUTO (NOME, PRECO) VALUES ('Feijão', 4);
INSERT INTO TB_PRODUTO (NOME, PRECO) VALUES ('Tomate', 2.5);
INSERT INTO TB_PRODUTO (NOME, PRECO) VALUES ('Batata', 3);

INSERT INTO TB_PEDIDO_STATUS (DS_STATUS) VALUES ('ABERTO');
INSERT INTO TB_PEDIDO_STATUS (DS_STATUS) VALUES ('CONCLUIDO');
INSERT INTO TB_PEDIDO_STATUS (DS_STATUS) VALUES ('CANCELADO');

INSERT INTO TB_PEDIDO (DT_PEDIDO, ID_CLIENTE, ID_STATUS) VALUES (SYSDATE, 1, 1);
INSERT INTO TB_PEDIDO (DT_PEDIDO, ID_CLIENTE, ID_STATUS) VALUES (SYSDATE, 2, 1);

INSERT INTO TB_PEDIDO_ITEM (ID_PEDIDO, ID_PRODUTO, QUANTIDADE) VALUES (1, 1, 5);
INSERT INTO TB_PEDIDO_ITEM (ID_PEDIDO, ID_PRODUTO, QUANTIDADE) VALUES (1, 2, 10);
INSERT INTO TB_PEDIDO_ITEM (ID_PEDIDO, ID_PRODUTO, QUANTIDADE) VALUES (1, 3, 11);
INSERT INTO TB_PEDIDO_ITEM (ID_PEDIDO, ID_PRODUTO, QUANTIDADE) VALUES (2, 1, 5);
INSERT INTO TB_PEDIDO_ITEM (ID_PEDIDO, ID_PRODUTO, QUANTIDADE) VALUES (2, 4, 10);